language: objective-c
script:
- set -o pipefail
- xcodebuild test -workspace ParallaxPagingViewControllerExample/ParallaxPagingViewControllerExample.xcworkspace -scheme ParallaxPagingViewControllerExample -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=latest'
- pod lib lint