language: objective-c
script:
- xcodebuild test -workspace ParallaxPagingViewControllerExample/ParallaxPagingViewControllerExample.xcworkspace -scheme ParallaxPagingViewControllerExample -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6s,OS=latest'
- pod lib lint