language: objective-c

osx_image: xcode8.2

podfile: ParallaxPagingViewControllerExample/Podfile

script:
- set -o pipefail
- xcodebuild -workspace ParallaxPagingViewControllerExample/ParallaxPagingViewControllerExample.xcworkspace -scheme ParallaxPagingViewControllerExample -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=latest' clean test
- pod lib lint